version: "3.8"

services:
    # 1. Laravel Application
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_smart_order_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - db
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_HOST=${DB_HOST}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    # 2. MySQL Database
    db:
        image: mysql:8.0
        container_name: mysql_smart_order_db
        restart: unless-stopped
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

    # 3. Nginx Web Server
    webserver:
        image: nginx:latest
        container_name: nginx_smart_order_server
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

networks:
    laravel_network:

volumes:
    db_data:
